spring.application.name=employee-management-system

# database properties
# to connect DB locally
#spring.datasource.url = jdbc:postgresql://localhost:5432/ems_db
# to connect DB locally with docker
spring.datasource.url = jdbc:postgresql://host.docker.internal:5432/ems_db
spring.datasource.username = postgres
spring.datasource.password = welcome
spring.datasource.driver-class-name = org.postgresql.Driver

#JPA settings
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

nazeeruddin.test.path=test
sravani.test.path=test
